export const Country = [
  { name: "Afghanistan", dial_code: "+93", code: "AF", phone_length: 9 },
  { name: "Albania", dial_code: "+355", code: "AL", phone_length: 9 },
  { name: "Algeria", dial_code: "+213", code: "DZ", phone_length: 9 },
  { name: "American Samoa", dial_code: "+1684", code: "AS", phone_length: 10 },
  { name: "Andorra", dial_code: "+376", code: "AD", phone_length: 6 },
  { name: "Angola", dial_code: "+244", code: "AO", phone_length: 9 },
  { name: "Anguilla", dial_code: "+1264", code: "AI", phone_length: 10 },
  { name: "Antarctica", dial_code: "+672", code: "AQ", phone_length: 9 },
  {
    name: "Antigua and Barbuda",
    dial_code: "+1268",
    code: "AG",
    phone_length: 10,
  },
  { name: "Argentina", dial_code: "+54", code: "AR", phone_length: 10 },
  { name: "Armenia", dial_code: "+374", code: "AM", phone_length: 8 },
  { name: "Aruba", dial_code: "+297", code: "AW", phone_length: 7 },
  { name: "Australia", dial_code: "+61", code: "AU", phone_length: 9 },
  { name: "Austria", dial_code: "+43", code: "AT", phone_length: 10 },
  { name: "Azerbaijan", dial_code: "+994", code: "AZ", phone_length: 9 },
  { name: "Bahamas", dial_code: "+1242", code: "BS", phone_length: 10 },
  { name: "Bahrain", dial_code: "+973", code: "BH", phone_length: 8 },
  { name: "Bangladesh", dial_code: "+880", code: "BD", phone_length: 10 },
  { name: "Barbados", dial_code: "+1246", code: "BB", phone_length: 10 },
  { name: "Belarus", dial_code: "+375", code: "BY", phone_length: 9 },
  { name: "Belgium", dial_code: "+32", code: "BE", phone_length: 9 },
  { name: "Belize", dial_code: "+501", code: "BZ", phone_length: 7 },
  { name: "Benin", dial_code: "+229", code: "BJ", phone_length: 9 },
  { name: "Bermuda", dial_code: "+1441", code: "BM", phone_length: 10 },
  { name: "Bhutan", dial_code: "+975", code: "BT", phone_length: 8 },
  {
    name: "Bolivia, Plurinational State of",
    dial_code: "+591",
    code: "BO",
    phone_length: 8,
  },
  {
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    code: "BA",
    phone_length: 8,
  },
  { name: "Botswana", dial_code: "+267", code: "BW", phone_length: 8 },
  { name: "Brazil", dial_code: "+55", code: "BR", phone_length: 11 },
  {
    name: "British Indian Ocean Territory",
    dial_code: "+246",
    code: "IO",
    phone_length: 7,
  },
  { name: "Brunei Darussalam", dial_code: "+673", code: "BN", phone_length: 7 },
  { name: "Bulgaria", dial_code: "+359", code: "BG", phone_length: 9 },
  { name: "Burkina Faso", dial_code: "+226", code: "BF", phone_length: 8 },
  { name: "Burundi", dial_code: "+257", code: "BI", phone_length: 8 },
  { name: "Cambodia", dial_code: "+855", code: "KH", phone_length: 9 },
  { name: "Cameroon", dial_code: "+237", code: "CM", phone_length: 9 },
  { name: "Canada", dial_code: "+1", code: "CA", phone_length: 10 },
  { name: "Cape Verde", dial_code: "+238", code: "CV", phone_length: 7 },
  { name: "Cayman Islands", dial_code: "+1345", code: "KY", phone_length: 10 },
  {
    name: "Central African Republic",
    dial_code: "+236",
    code: "CF",
    phone_length: 8,
  },
  { name: "Chad", dial_code: "+235", code: "TD", phone_length: 8 },
  { name: "Chile", dial_code: "+56", code: "CL", phone_length: 9 },
  { name: "China", dial_code: "+86", code: "CN", phone_length: 11 },
  { name: "Christmas Island", dial_code: "+61", code: "CX", phone_length: 9 },
  {
    name: "Cocos (Keeling) Islands",
    dial_code: "+61",
    code: "CC",
    phone_length: 9,
  },
  { name: "Colombia", dial_code: "+57", code: "CO", phone_length: 10 },
  { name: "Comoros", dial_code: "+269", code: "KM", phone_length: 7 },
  { name: "Congo", dial_code: "+242", code: "CG", phone_length: 9 },
  {
    name: "Congo, The Democratic Republic of the",
    dial_code: "+243",
    code: "CD",
    phone_length: 9,
  },
  { name: "Cook Islands", dial_code: "+682", code: "CK", phone_length: 5 },
  { name: "Costa Rica", dial_code: "+506", code: "CR", phone_length: 8 },
  { name: "Cote d'Ivoire", dial_code: "+225", code: "CI", phone_length: 10 },
  { name: "Croatia", dial_code: "+385", code: "HR", phone_length: 9 },
  { name: "Cuba", dial_code: "+53", code: "CU", phone_length: 8 },
  { name: "Cyprus", dial_code: "+357", code: "CY", phone_length: 8 },
  { name: "Czech Republic", dial_code: "+420", code: "CZ", phone_length: 9 },
  { name: "Denmark", dial_code: "+45", code: "DK", phone_length: 8 },
  { name: "Djibouti", dial_code: "+253", code: "DJ", phone_length: 8 },
  { name: "Dominica", dial_code: "+1767", code: "DM", phone_length: 10 },
  {
    name: "Dominican Republic",
    dial_code: "+1849",
    code: "DO",
    phone_length: 10,
  },
  { name: "Ecuador", dial_code: "+593", code: "EC", phone_length: 9 },
  { name: "Egypt", dial_code: "+20", code: "EG", phone_length: 10 },
  { name: "El Salvador", dial_code: "+503", code: "SV", phone_length: 8 },
  { name: "Equatorial Guinea", dial_code: "+240", code: "GQ", phone_length: 9 },
  { name: "Eritrea", dial_code: "+291", code: "ER", phone_length: 7 },
  { name: "Estonia", dial_code: "+372", code: "EE", phone_length: 8 },
  { name: "Ethiopia", dial_code: "+251", code: "ET", phone_length: 9 },
  {
    name: "Falkland Islands (Malvinas)",
    dial_code: "+500",
    code: "FK",
    phone_length: 5,
  },
  { name: "Faroe Islands", dial_code: "+298", code: "FO", phone_length: 6 },
  { name: "Fiji", dial_code: "+679", code: "FJ", phone_length: 7 },
  { name: "Finland", dial_code: "+358", code: "FI", phone_length: 10 },
  { name: "France", dial_code: "+33", code: "FR", phone_length: 9 },
  { name: "French Guiana", dial_code: "+594", code: "GF", phone_length: 9 },
  { name: "French Polynesia", dial_code: "+689", code: "PF", phone_length: 6 },
  { name: "Gabon", dial_code: "+241", code: "GA", phone_length: 7 },
  { name: "Gambia", dial_code: "+220", code: "GM", phone_length: 7 },
  { name: "Georgia", dial_code: "+995", code: "GE", phone_length: 9 },
  { name: "Germany", dial_code: "+49", code: "DE", phone_length: 10 },
  { name: "Ghana", dial_code: "+233", code: "GH", phone_length: 9 },
  { name: "Gibraltar", dial_code: "+350", code: "GI", phone_length: 8 },
  { name: "Greece", dial_code: "+30", code: "GR", phone_length: 10 },
  { name: "Greenland", dial_code: "+299", code: "GL", phone_length: 6 },
  { name: "Grenada", dial_code: "+1473", code: "GD", phone_length: 10 },
  { name: "Guadeloupe", dial_code: "+590", code: "GP", phone_length: 9 },
  { name: "Guam", dial_code: "+1671", code: "GU", phone_length: 10 },
  { name: "Guatemala", dial_code: "+502", code: "GT", phone_length: 8 },
  { name: "Guernsey", dial_code: "+44", code: "GG", phone_length: 10 },
  { name: "Guinea", dial_code: "+224", code: "GN", phone_length: 9 },
  { name: "Guinea-Bissau", dial_code: "+245", code: "GW", phone_length: 7 },
  { name: "Guyana", dial_code: "+592", code: "GY", phone_length: 7 },
  { name: "Haiti", dial_code: "+509", code: "HT", phone_length: 8 },
  {
    name: "Holy See (Vatican City State)",
    dial_code: "+379",
    code: "VA",
    phone_length: 10,
  },
  { name: "Honduras", dial_code: "+504", code: "HN", phone_length: 8 },
  { name: "Hong Kong", dial_code: "+852", code: "HK", phone_length: 8 },
  { name: "Hungary", dial_code: "+36", code: "HU", phone_length: 9 },
  { name: "Iceland", dial_code: "+354", code: "IS", phone_length: 7 },
  { name: "India", dial_code: "+91", code: "IN", phone_length: 10 },
  { name: "Indonesia", dial_code: "+62", code: "ID", phone_length: 10 },
  {
    name: "Iran, Islamic Republic of",
    dial_code: "+98",
    code: "IR",
    phone_length: 10,
  },
  { name: "Iraq", dial_code: "+964", code: "IQ", phone_length: 10 },
  { name: "Ireland", dial_code: "+353", code: "IE", phone_length: 9 },
  { name: "Isle of Man", dial_code: "+44", code: "IM", phone_length: 10 },
  { name: "Israel", dial_code: "+972", code: "IL", phone_length: 9 },
  { name: "Italy", dial_code: "+39", code: "IT", phone_length: 10 },
  { name: "Jamaica", dial_code: "+1876", code: "JM", phone_length: 10 },
  { name: "Japan", dial_code: "+81", code: "JP", phone_length: 10 },
  { name: "Jersey", dial_code: "+44", code: "JE", phone_length: 10 },
  { name: "Jordan", dial_code: "+962", code: "JO", phone_length: 9 },
  { name: "Kazakhstan", dial_code: "+77", code: "KZ", phone_length: 10 },
  { name: "Kenya", dial_code: "+254", code: "KE", phone_length: 10 },
  { name: "Kiribati", dial_code: "+686", code: "KI", phone_length: 8 },
  {
    name: "Korea, Democratic People's Republic of",
    dial_code: "+850",
    code: "KP",
    phone_length: 10,
  },
  { name: "Korea, Republic of", dial_code: "+82", code: "KR", phone_length: 9 },
  { name: "Kuwait", dial_code: "+965", code: "KW", phone_length: 8 },
  { name: "Kyrgyzstan", dial_code: "+996", code: "KG", phone_length: 9 },
  {
    name: "Lao People's Democratic Republic",
    dial_code: "+856",
    code: "LA",
    phone_length: 9,
  },
  { name: "Latvia", dial_code: "+371", code: "LV", phone_length: 8 },
  { name: "Lebanon", dial_code: "+961", code: "LB", phone_length: 8 },
  { name: "Lesotho", dial_code: "+266", code: "LS", phone_length: 8 },
  { name: "Liberia", dial_code: "+231", code: "LR", phone_length: 7 },
  { name: "Libya", dial_code: "+218", code: "LY", phone_length: 9 },
  { name: "Liechtenstein", dial_code: "+423", code: "LI", phone_length: 7 },
  { name: "Lithuania", dial_code: "+370", code: "LT", phone_length: 8 },
  { name: "Luxembourg", dial_code: "+352", code: "LU", phone_length: 9 },
  { name: "Macao", dial_code: "+853", code: "MO", phone_length: 8 },
  {
    name: "Macedonia, The Former Yugoslav Republic of",
    dial_code: "+389",
    code: "MK",
    phone_length: 8,
  },
  { name: "Madagascar", dial_code: "+261", code: "MG", phone_length: 9 },
  { name: "Malawi", dial_code: "+265", code: "MW", phone_length: 9 },
  { name: "Malaysia", dial_code: "+60", code: "MY", phone_length: 9 },
  { name: "Maldives", dial_code: "+960", code: "MV", phone_length: 7 },
  { name: "Mali", dial_code: "+223", code: "ML", phone_length: 8 },
  { name: "Malta", dial_code: "+356", code: "MT", phone_length: 8 },
  { name: "Marshall Islands", dial_code: "+692", code: "MH", phone_length: 7 },
  { name: "Martinique", dial_code: "+596", code: "MQ", phone_length: 9 },
  { name: "Mauritania", dial_code: "+222", code: "MR", phone_length: 8 },
  { name: "Mauritius", dial_code: "+230", code: "MU", phone_length: 7 },
  { name: "Mayotte", dial_code: "+262", code: "YT", phone_length: 9 },
  { name: "Mexico", dial_code: "+52", code: "MX", phone_length: 10 },
  {
    name: "Micronesia, Federated States of",
    dial_code: "+691",
    code: "FM",
    phone_length: 7,
  },
  {
    name: "Moldova, Republic of",
    dial_code: "+373",
    code: "MD",
    phone_length: 8,
  },
  { name: "Monaco", dial_code: "+377", code: "MC", phone_length: 8 },
  { name: "Mongolia", dial_code: "+976", code: "MN", phone_length: 8 },
  { name: "Montenegro", dial_code: "+382", code: "ME", phone_length: 8 },
  { name: "Montserrat", dial_code: "+1664", code: "MS", phone_length: 10 },
  { name: "Morocco", dial_code: "+212", code: "MA", phone_length: 9 },
  { name: "Mozambique", dial_code: "+258", code: "MZ", phone_length: 9 },
  { name: "Myanmar", dial_code: "+95", code: "MM", phone_length: 9 },
  { name: "Namibia", dial_code: "+264", code: "NA", phone_length: 9 },
  { name: "Nauru", dial_code: "+674", code: "NR", phone_length: 7 },
  { name: "Nepal", dial_code: "+977", code: "NP", phone_length: 10 },
  { name: "Netherlands", dial_code: "+31", code: "NL", phone_length: 9 },
  {
    name: "Netherlands Antilles",
    dial_code: "+599",
    code: "AN",
    phone_length: 7,
  },
  { name: "New Caledonia", dial_code: "+687", code: "NC", phone_length: 6 },
  { name: "New Zealand", dial_code: "+64", code: "NZ", phone_length: 9 },
  { name: "Nicaragua", dial_code: "+505", code: "NI", phone_length: 8 },
  { name: "Niger", dial_code: "+227", code: "NE", phone_length: 8 },
  { name: "Nigeria", dial_code: "+234", code: "NG", phone_length: 10 },
  { name: "Niue", dial_code: "+683", code: "NU", phone_length: 4 },
  { name: "Norfolk Island", dial_code: "+672", code: "NF", phone_length: 6 },
  {
    name: "Northern Mariana Islands",
    dial_code: "+1670",
    code: "MP",
    phone_length: 10,
  },
  { name: "Norway", dial_code: "+47", code: "NO", phone_length: 8 },
  { name: "Oman", dial_code: "+968", code: "OM", phone_length: 8 },
  { name: "Pakistan", dial_code: "+92", code: "PK", phone_length: 10 },
  { name: "Palau", dial_code: "+680", code: "PW", phone_length: 7 },
  {
    name: "Palestinian Territory, Occupied",
    dial_code: "+970",
    code: "PS",
    phone_length: 9,
  },
  { name: "Panama", dial_code: "+507", code: "PA", phone_length: 8 },
  { name: "Papua New Guinea", dial_code: "+675", code: "PG", phone_length: 8 },
  { name: "Paraguay", dial_code: "+595", code: "PY", phone_length: 9 },
  { name: "Peru", dial_code: "+51", code: "PE", phone_length: 9 },
  { name: "Philippines", dial_code: "+63", code: "PH", phone_length: 10 },
  { name: "Pitcairn", dial_code: "+872", code: "PN", phone_length: 6 },
  { name: "Poland", dial_code: "+48", code: "PL", phone_length: 9 },
  { name: "Portugal", dial_code: "+351", code: "PT", phone_length: 9 },
  { name: "Puerto Rico", dial_code: "+1939", code: "PR", phone_length: 10 },
  { name: "Qatar", dial_code: "+974", code: "QA", phone_length: 8 },
  { name: "Romania", dial_code: "+40", code: "RO", phone_length: 10 },
  { name: "Russia", dial_code: "+7", code: "RU", phone_length: 10 },
  { name: "Rwanda", dial_code: "+250", code: "RW", phone_length: 9 },
  { name: "Reunion", dial_code: "+262", code: "RE", phone_length: 9 },
  {
    name: "Saint Barthelemy",
    dial_code: "+590",
    code: "BL",
    phone_length: 9,
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dial_code: "+290",
    code: "SH",
    phone_length: 4,
  },
  {
    name: "Saint Kitts and Nevis",
    dial_code: "+1869",
    code: "KN",
    phone_length: 10,
  },
  { name: "Saint Lucia", dial_code: "+1758", code: "LC", phone_length: 10 },
  { name: "Saint Martin", dial_code: "+590", code: "MF", phone_length: 9 },
  {
    name: "Saint Pierre and Miquelon",
    dial_code: "+508",
    code: "PM",
    phone_length: 6,
  },
  {
    name: "Saint Vincent and the Grenadines",
    dial_code: "+1784",
    code: "VC",
    phone_length: 10,
  },
  { name: "Samoa", dial_code: "+685", code: "WS", phone_length: 7 },
  { name: "San Marino", dial_code: "+378", code: "SM", phone_length: 9 },
  {
    name: "Sao Tome and Principe",
    dial_code: "+239",
    code: "ST",
    phone_length: 7,
  },
  { name: "Saudi Arabia", dial_code: "+966", code: "SA", phone_length: 9 },
  { name: "Senegal", dial_code: "+221", code: "SN", phone_length: 9 },
  { name: "Serbia", dial_code: "+381", code: "RS", phone_length: 9 },
  { name: "Seychelles", dial_code: "+248", code: "SC", phone_length: 7 },
  { name: "Sierra Leone", dial_code: "+232", code: "SL", phone_length: 8 },
  { name: "Singapore", dial_code: "+65", code: "SG", phone_length: 8 },
  { name: "Slovakia", dial_code: "+421", code: "SK", phone_length: 9 },
  { name: "Slovenia", dial_code: "+386", code: "SI", phone_length: 9 },
  { name: "Solomon Islands", dial_code: "+677", code: "SB", phone_length: 7 },
  { name: "Somalia", dial_code: "+252", code: "SO", phone_length: 7 },
  { name: "South Africa", dial_code: "+27", code: "ZA", phone_length: 9 },
  { name: "South Sudan", dial_code: "+211", code: "SS", phone_length: 9 },
  {
    name: "South Georgia and the South Sandwich Islands",
    dial_code: "+500",
    code: "GS",
    phone_length: 4,
  },
  { name: "Spain", dial_code: "+34", code: "ES", phone_length: 9 },
  { name: "Sri Lanka", dial_code: "+94", code: "LK", phone_length: 9 },
  { name: "Sudan", dial_code: "+249", code: "SD", phone_length: 9 },
  { name: "Suriname", dial_code: "+597", code: "SR", phone_length: 7 },
  {
    name: "Svalbard and Jan Mayen",
    dial_code: "+47",
    code: "SJ",
    phone_length: 8,
  },
  { name: "Swaziland", dial_code: "+268", code: "SZ", phone_length: 8 },
  { name: "Sweden", dial_code: "+46", code: "SE", phone_length: 9 },
  { name: "Switzerland", dial_code: "+41", code: "CH", phone_length: 9 },
  {
    name: "Syrian Arab Republic",
    dial_code: "+963",
    code: "SY",
    phone_length: 9,
  },
  { name: "Taiwan", dial_code: "+886", code: "TW", phone_length: 9 },
  { name: "Tajikistan", dial_code: "+992", code: "TJ", phone_length: 9 },
  {
    name: "Tanzania, United Republic of",
    dial_code: "+255",
    code: "TZ",
    phone_length: 9,
  },
  { name: "Thailand", dial_code: "+66", code: "TH", phone_length: 9 },
  { name: "Timor-Leste", dial_code: "+670", code: "TL", phone_length: 8 },
  { name: "Togo", dial_code: "+228", code: "TG", phone_length: 8 },
  { name: "Tokelau", dial_code: "+690", code: "TK", phone_length: 4 },
  { name: "Tonga", dial_code: "+676", code: "TO", phone_length: 5 },
  {
    name: "Trinidad and Tobago",
    dial_code: "+1868",
    code: "TT",
    phone_length: 10,
  },
  { name: "Tunisia", dial_code: "+216", code: "TN", phone_length: 8 },
  { name: "Turkey", dial_code: "+90", code: "TR", phone_length: 10 },
  { name: "Turkmenistan", dial_code: "+993", code: "TM", phone_length: 8 },
  {
    name: "Turks and Caicos Islands",
    dial_code: "+1649",
    code: "TC",
    phone_length: 10,
  },
  { name: "Tuvalu", dial_code: "+688", code: "TV", phone_length: 5 },
  { name: "Uganda", dial_code: "+256", code: "UG", phone_length: 9 },
  { name: "Ukraine", dial_code: "+380", code: "UA", phone_length: 9 },
  {
    name: "United Arab Emirates",
    dial_code: "+971",
    code: "AE",
    phone_length: 9,
  },
  { name: "United Kingdom", dial_code: "+44", code: "GB", phone_length: 10 },
  { name: "United States", dial_code: "+1", code: "US", phone_length: 10 },
  { name: "Uruguay", dial_code: "+598", code: "UY", phone_length: 8 },
  { name: "Uzbekistan", dial_code: "+998", code: "UZ", phone_length: 9 },
  { name: "Vanuatu", dial_code: "+678", code: "VU", phone_length: 7 },
  {
    name: "Venezuela, Bolivarian Republic of",
    dial_code: "+58",
    code: "VE",
    phone_length: 10,
  },
  { name: "Vietnam", dial_code: "+84", code: "VN", phone_length: 9 },
  {
    name: "Virgin Islands, British",
    dial_code: "+1284",
    code: "VG",
    phone_length: 10,
  },
  {
    name: "Virgin Islands, U.S.",
    dial_code: "+1340",
    code: "VI",
    phone_length: 10,
  },
  {
    name: "Wallis and Futuna",
    dial_code: "+681",
    code: "WF",
    phone_length: 6,
  },
  { name: "Yemen", dial_code: "+967", code: "YE", phone_length: 9 },
  { name: "Zambia", dial_code: "+260", code: "ZM", phone_length: 9 },
  { name: "Zimbabwe", dial_code: "+263", code: "ZW", phone_length: 9 },
];
